backend:
  name: git-gateway
  branch: main

locale: "pt"
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  # -------------------- TEMA --------------------
  - name: theme
    label: "Tema (cores e WhatsApp)"
    delete: false
    files:
      - file: "content/theme.json"
        name: theme
        label: "Configurações do Tema"
        format: json
        fields:
          # CORES (não mudei os nomes dos campos)
          - { label: "Cor principal (títulos/destaques)",       name: primaryColor,   widget: color, allowInput: true, default: "#58410d", hint: "Usada nos títulos e elementos de destaque." }
          - { label: "Cor de apoio (detalhes)",                  name: secondaryColor, widget: color, allowInput: true, required: false, default: "#7a5c4b", hint: "Detalhes como ícones e bordas sutis." }
          - { label: "Fundo do site",                            name: backgroundColor,widget: color, allowInput: true, required: false, default: "#f8f6f3", hint: "Cor do plano de fundo das páginas." }
          - { label: "Cor do texto (parágrafos)",                name: textColor,      widget: color, allowInput: true, required: false, default: "#5a4b42", hint: "Cor do texto comum." }
          - { label: "Botões e tags ativas",                    name: buttonColor,    widget: color, allowInput: true, required: false, default: "#d99a9a", hint: "Cor dos botões e filtros ativos." }
          - { label: "Cor dos cartões (área dos produtos)",      name: card,           widget: color, allowInput: true, required: false, default: "#ffffff", hint: "Fundo dos cards de produto." }

          # WHATSAPP
          - { label: "WhatsApp (com DDI)",                       name: whatsapp,          widget: string, required: false, default: "+55 11999999999", hint: "Ex.: +55 11999999999" }
          - { label: "Mensagem padrão do WhatsApp",              name: whatsappMessage,   widget: string, required: false, default: "Olá! Quero fazer um pedido 😊", hint: "Texto inicial ao clicar no botão." }

          # OUTROS
          - { label: "Mostrar seção 'Sobre'",                    name: showAbout, widget: boolean, default: true, hint: "Liga/desliga a seção Sobre na página." }

  # -------------------- HERO --------------------
  - name: hero
    label: "Banner (capa)"
    delete: false
    files:
      - file: "content/hero.json"
        name: hero
        label: "Seção Banner (capa)"
        format: json
        fields:
          - { label: "Título grande do banner",       name: title,            widget: string, default: "Sua Celebração, Nossa Assinatura" }
          - { label: "Subtítulo (frase abaixo)",      name: subtitle,         widget: text, required: false, default: "Bolos decorados sob medida para momentos que merecem ser lembrados." }
          - { label: "Imagem de fundo do banner",     name: image,            widget: image, required: false, default: "images/hero.jpg" }
          - { label: "Opacidade do efeito (0–1)",     name: overlayOpacity,   widget: number, min: 0, max: 1, step: 0.05, required: false, default: 0.5, hint: "Quanto maior, mais escuro o efeito sobre a imagem." }
          - { label: "Texto do botão",                name: ctaText,          widget: string, required: false, default: "Ver Cardápio" }
          - { label: "Link do botão",                 name: ctaLink,          widget: string, required: false, default: "#menu" }

  # -------------------- SOBRE --------------------
  - name: about
    label: "Sobre você ou ateliê"
    delete: false
    files:
      - file: "content/about.json"
        name: about
        label: "Seção Sobre"
        format: json
        fields:
          - { label: "Título da seção", name: title, widget: string, default: "Sobre" }
          - { label: "Texto de apresentação", name: text, widget: text, default: "Olá! Somos especializados em bolos decorados com buttercream, feitos com carinho e ingredientes selecionados." }
          - { label: "Imagem (opcional)", name: image, widget: image, required: false, default: "images/about.jpg" }
          - label: "Diferenciais (lista opcional)"
            name: features
            widget: list
            allow_add: true
            fields:
              - { label: "Ícone (opcional)",  name: icon,  widget: image, required: false }
              - { label: "Título",            name: title, widget: string }
              - { label: "Texto",             name: text,  widget: text }

  # -------------------- CATEGORIAS --------------------
  - name: categories
    label: "Categorias (filtros)"
    files:
      - file: "content/categories.json"
        name: categories
        label: "Categorias"
        format: json
        fields:
          - label: "Itens"
            name: items
            widget: list
            fields:
              - { label: "Nome visível",  name: name,  widget: string }
              - { label: "Slug (sem espaço, minúsculo)",  name: slug,  widget: string, hint: "Ex.: especiais, tradicionais" }
              - { label: "Ordem (opcional)", name: order, widget: number, required: false }
            default:
              - { name: "Especiais",    slug: "especiais",    order: 1 }
              - { name: "Tradicionais", slug: "tradicionais", order: 2 }

  # -------------------- PRODUTOS --------------------
  - name: products
    label: "Produtos (bolos)"
    files:
      - file: "content/products.json"
        name: products
        label: "Produtos"
        format: json
        fields:
          - label: "Itens"
            name: items
            widget: list
            allow_add: true
            fields:
              - { label: "Ativo",                 name: active,      widget: boolean, default: true }
              - { label: "Nome do bolo",          name: name,        widget: string }
              - { label: "Descrição",             name: description, widget: text, required: false }
              - { label: "Categoria (slug)",      name: category,    widget: string, required: false, hint: "Use exatamente o slug da categoria (ex.: especiais)." }
              - { label: "Preço padrão (opcional)", name: price,     widget: string, required: false, hint: "Você pode detalhar por tamanho abaixo." }
              - { label: "Imagem do produto",     name: image,       widget: image, required: false }
              - label: "Tamanhos (opcional)"
                name: sizes
                widget: list
                required: false
                fields:
                  - { label: "Nome (P/M/G…)", name: label, widget: string }
                  - { label: "Preço",         name: price, widget: string, required: false }
                default:
                  - { label: "P", price: "" }
                  - { label: "M", price: "" }
                  - { label: "G", price: "" }
              - { label: "Etiqueta (opcional)", name: badge, widget: select, required: false, options: ["Novo", "Mais vendido", "Promoção"] }
              - { label: "Ordem (opcional)", name: order, widget: number, required: false }

  # -------------------- DECORAÇÕES --------------------
  - name: decorations
    label: "Decorações"
    files:
      - file: "content/decorations.json"
        name: decorations
        label: "Decorações"
        format: json
        fields:
          - label: "Itens"
            name: items
            widget: list
            fields:
              - { label: "Nome",   name: name,  widget: string }
              - { label: "Imagem", name: image, widget: image, required: false }

  # -------------------- GALERIA (do template) --------------------
  - name: gallery
    label: "Galeria"
    files:
      - file: "content/gallery.json"
        name: gallery
        label: "Galeria"
        format: json
        fields:
          - label: "Imagens"
            name: images
            widget: list
            field:
              label: "Imagem"
              name: image
              widget: image

  # -------------------- INFORMAÇÕES/POLÍTICAS --------------------
  - name: policies
    label: "Informações/Políticas"
    files:
      - file: "content/policies.json"
        name: policies
        label: "Informações/Políticas"
        format: json
        fields:
          - { label: "Título da seção", name: title, widget: string, default: "Informações & Políticas" }
          - label: "Blocos de informação"
            name: items
            widget: list
            fields:
              - { label: "Título", name: title, widget: string }
              - { label: "Texto",  name: text,  widget: text }
              - { label: "Ícone (opcional)",  name: icon,  widget: image, required: false }

  # -------------------- FAQ --------------------
  - name: faq
    label: "FAQ"
    files:
      - file: "content/faq.json"
        name: faq
        label: "FAQ"
        format: json
        fields:
          - label: "Perguntas"
            name: items
            widget: list
            fields:
              - { label: "Pergunta", name: question, widget: string }
              - { label: "Resposta", name: answer,   widget: text }
